### ISSUE TITLE
Change step color.

### ISSUE THREAD

**Issue by blackcolt** [Johnykutty/JKSteppedProgressBar#1]
Is there any way to change the color of one step instead of all?

**Comment by jkmathew** [comment]
Right now, its not possible.
Because, its planned to change the colors in incrementing way. That is, if the `currentTab ` value is 3, all steps up to 3 will be in active color and all steps after that will be in inactive color.

**Comment by jayahariv** [comment]
Added a step color feature, which will change the whole steps till the current tab. Is this something you are expecting?

<img width="160" alt="step1" src="https://user-images.githubusercontent.com/10448770/39323042-6a3027f2-4940-11e8-83f7-051765b3a4bb.png"> <img width="160" alt="step2" src="https://user-images.githubusercontent.com/10448770/39323044-6a4c9b1c-4940-11e8-8f90-ba9407f1366d.png"> <img width="160" alt="step3" src="https://user-images.githubusercontent.com/10448770/39323045-6a689f24-4940-11e8-9620-e80a9721acc5.png">

**Comment by jkmathew** [comment]
I think he mentioned something like different dill color for different tabs.
@jayahariv this current implementation we can achieve even w/o new change.

Let me check whether I can implement the fill color mode.

I am taking this

**Comment by jkmathew** [comment]
@jayahariv  pls have a look at branch `different_colors` 
Made changes to draw different colours for different steps, if colours provided


![screen shot](https://user-images.githubusercontent.com/1732366/39408907-68c8c6ae-4bfb-11e8-9825-b6812c2ac40a.png)

**Comment by jayahariv** [comment]
# Awesome, Johny

Let's close this!
