### ISSUE TITLE
Code of Latest version in pod for Adding Images

### ISSUE THREAD

**Issue by eshajari** [Johnykutty/JKSteppedProgressBar#19]
Hi Team,
Thanks for the great lib.
I added pod for `pod 'JKSteppedProgressBar'` to the app, but that is having a older code which doesn't support images as param to be pass.

In the given code I can found that it is there. 

How can I take the latest version via pod ? please help on the same.

**Comment by jkmathew** [comment]
Hello @Eshajari,
Could you try 'pod repo update' then 'pod install'. If that doesnt work, could you share your terminal output?

Regards,
Johny

**Comment by eshajari** [comment]
After 'pod repo update' I try 'pod install' but that install the version 0.3.0

`Installing JKSteppedProgressBar (0.3.0)
`
I am currently trying by adding the code file to the app rather then the pod .

Thanks for the reply .

**Comment by jkmathew** [comment]
Hi @eshajari ,
You may try again now, I have pushed latest podspec.

**Comment by jkmathew** [comment]
Closing since inactivity.

Feel free to reopen if issue exists :)

**Comment by somasharma95** [comment]
I am also having the same problem
