### ISSUE TITLE
How to scroll progress bar

### ISSUE THREAD

**Issue by talkabhishek** [Johnykutty/JKSteppedProgressBar#23]
I tried adding it to scroll view and searched for some property to allow scrolling
It cut from left and right when step increases along with circle spacing
<img width="318" alt="Screenshot 2019-05-22 at 8 55 37 AM" src="https://user-images.githubusercontent.com/26160090/58145359-6937f600-7c6f-11e9-8127-c302c7596d7b.png">

**Comment by jkmathew** [comment]
Actually, scrolling is not indented for this control, Like normal progress bar,slider etc.

You could wrap this inside a scrollview if required.

**Comment by sajidjutt7** [comment]
@jkmathew you have closed this issue. But the problem was with progress bar. I have wrapped the progress bar inside scrollview. Still not working. I have put some other things in that scrollview and its scrolling fine.

**Comment by sajidjutt7** [comment]
@talkabhishek have you found solution of this problem? If so please can you elaborate. Thanks
