### ISSUE TITLE
If titles have several lines, only first line is visible

### ISSUE THREAD

**Issue by sarbogast** [Johnykutty/JKSteppedProgressBar#25]
Some of my step titles are too long and end up overlapping. I was hoping the titles would automatically wrap so as not to overlap but they didn't. So then I tried replacing spaces by new lines, but then only the first line appears:

<img width="1341" alt="Screenshot 2019-07-11 12 56 46" src="https://user-images.githubusercontent.com/143758/61045692-a1d88e00-a3db-11e9-9641-b31cfaf5deb8.png">

**Comment by jkmathew** [comment]
@sarbogast 
Thank you for reporting and sorry for the delay in response.

This is now fixed, but not updated in pod spec repo.
You can use the latest version with following line in `Podfile`

```
pod 'JKSteppedProgressBar', :git=> 'https://github.com/jkmathew/JKSteppedProgressBar.git'
```

**Comment by khaledannajar** [comment]
Hello, when are you going to release this last update?
