### ISSUE TITLE
spacing between circle and text

### ISSUE THREAD

**Issue by kiranruth** [Johnykutty/JKSteppedProgressBar#3]
![image](https://cloud.githubusercontent.com/assets/626526/26439115/3ea1e18e-4144-11e7-9a26-ff64df36e2a2.png)

How do I increase the space between the circle and the tab ??
Also, it would be best if the inactive line doesn't overlap with the active tab

**Comment by jkmathew** [comment]
Added ability to adjust spacing between circle and title.
Inactive line will not overlap now

**Comment by kiranruth** [comment]
Thanks much !

Thanks & regards,
Kiran Ruth . R

Contact Info:
Skype  :  kiran_ruth
e-mail :  kiranruth@gmail.com / me@kiranruth.com
Mobile:  +91-9886116404


On Fri, Aug 18, 2017 at 2:52 PM, Johnykutty Mathew <notifications@github.com
