### ISSUE TITLE
Enhancement / Suggestion

### ISSUE THREAD

**Issue by agiguere** [Johnykutty/JKSteppedProgressBar#4]
Very nice control, I like it. But sometimes I don't want to have the step number display inside the circle, there should be an API to display the a completed step as a full circle vs an empty circle representing a step not completed

something like this
https://designmodo.com/wp-content/uploads/2013/02/711.jpg

thanks

**Comment by jkmathew** [comment]
Its a nice suggestion, I will look into that once i get enough time. :)

**Comment by jkmathew** [comment]
Its done in version 0.3.0 - not exactly like your sample screenshot.
Please have a look.
You can change the mode by adding following line of code
```
progressbar.stepDrawingMode = .fill
```
It will look like 
![screen shot 2017-09-11 at 2 39 49 pm](https://user-images.githubusercontent.com/1732366/30267190-614c7c9c-96ff-11e7-8aac-b12c069ba403.png)

**Comment by agiguere** [comment]
nice, very nice addition, thanks
