### ISSUE TITLE
how can I add different view controllers for each steps??

### ISSUE THREAD

**Issue by imtetch** [Johnykutty/JKSteppedProgressBar#6]
hii,sir could u please help me. I'm new to developing field ,I want to show the stepper in 5 view controllers as step by step process.. thank you in advance

**Comment by jkmathew** [comment]
Hello @imtetch , 
Actually this is not supposed to do something like that. `JKSteppedProgressBar` is only showing  progress/steps. 

You can create your own container view controller and hide/unhide the embedded view controllers based on the progress. Please find great read @ https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html
https://naveenr.net/beginning-container-views-in-ios/
